### ISSUE TITLE
CSS injection

### ISSUE THREAD

**Issue by garudaonekh** [s00500/ESPUI#123]
I think by adding CSS inject to the control, it would add more flexibility.

It can be as simple as ESPUI.updateCSS(controlid, "color:red;font-size:11").

Thanks;

**Comment by iangray001** [comment]
If you're interested in implementing this, I knocked together a proof of concept which allows you to give individual elements a custom style. It's pretty basic and needs tightening up but someone might find this useful.

https://github.com/iangray001/ESPUI/commit/82726b1d71b3ab2b9d8d8c52c89b719e287a9ffc

This lets you, for example, make a custom red button with:

```
ESPUI.addControl(ControlType::Button, "Save", "Save", ControlColor::Peterriver, tabname, &callback, "background-color: red;");
```

**Comment by s00500** [comment]
Hey @iangray001, that looks cool, the only comment I have is could you add a seperate function call for adding styles ? addControl is already such a overkill function... And when you do so do you mind adding a PR to this repository ?
Happy New year!

**Comment by iangray001** [comment]
Yeah that is probably a fair point. I stuck this in a branch simply because I was playing around, and I've since had a better idea of how to implement this. The way I've done this here is fundamentally static, but there is no reason why this couldn't work dynamically. Let me have a look over the next few days.
