### ISSUE TITLE
How to add an option after the ESPUI started?

### ISSUE THREAD

**Issue by nodoubtman** [s00500/ESPUI#153]
Hello. I'm wondering how to add an option after the others when the ESPUI have started already?

i tried that:

static String bufName = "Name";
static String bufUrl     = "My URL";

ESPUI.addControl( ControlType::Option, bufName, bufUrl, COLOR_TURQUOISE, radioWebOption );

but the programs crashed!

it cannot reload the UI after that.

Thanks for your help.
Marc.

**Comment by iangray001** [comment]
So that code doesn't compile. The second argument of `addControl` expects a `const char *` and you've given it a `String`. On my setup at least that is a compile error:

```
error: no matching function for call to 'ESPUIClass::addControl(ControlType, String&, String, ControlColor, uint16_t&)'
```

Changing it to `bufName.c_str()` works. You don't see the new option initially but if you refresh the UI with: `ESPUI.jsonReload();` then it's fine.

```
ESPUI.addControl(Option, bufName.c_str(), String(bufUrl), None, radioWebOption);
ESPUI.jsonReload();
```

Your crashing must be related to something else. Feel free to reopen if you're still having issues.
