### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by nodoubtman** [s00500/ESPUI#160]
Just a question: How do i update only one element with jsonDom();

i used to use ESPUI.jsonDom(0);

but if i can do better, why not?

Thanks.
Marc.

**Comment by iangray001** [comment]
I’m not sure I understand what you’re asking. 

`jsonDom` will resend the entire UI. We tend to not use that for updating just one control because it has to redraw the entire UI. 

Incidentally, rather than calling `jsonDom` the function that is supposed to be used for reloading the UI is`ESPUI.jsonReload()`.
