### ISSUE TITLE
Add gif animations?

### ISSUE THREAD

**Issue by serlancelot** [s00500/ESPUI#236]
Hello, good morning, one question... is there any way to add gif animations and make them work without a network connection?
Thanks greetings!

**Comment by iangray001** [comment]
A [data URI](https://css-tricks.com/data-uris/) would work. It's not pretty but you can base64 encode any image directly into the URL.

**Comment by serlancelot** [comment]
ok, I saw it in another message, but I thought it was only for a static image...
I'll look at it later to see if I can get it to work... thanks!  I'm sure you have some more questions

**Comment by serlancelot** [comment]
Well... I can't get it to come out.
If I put it this way, there is no problem, it loads the gif and the animation is perfectly visible.

`ESPUI.label("An Image Label", ControlColor::Peterriver, "<img src='https://i.gifer.com/origin/4d/4dc11d17f5292fd463a60aa2bbb41f6a_w200.webp'>");`

but if I try to put all the text in base64 it doesn't load it, besides I had to install the new version of the arduino IDE and modify the "editor.maxTokenizationLineLength" because it didn't recognize the whole line. But even so, it does not load, it does not load more than the graphic environment.
`  ESPUI.label("An Image Label", ControlColor::Peterriver, "<img src='data:image/gif;base64,XXXXXXXXXXXXX'>");`
The X is the whole line of text in base64
And in the serial monitor it gives the following error:
ERROR: prepareJSONChunk: Control 27 is too large to be sent to the browser.

I suppose the problem is due to the length... Is there any other way to be able to use "offline" animations?
Thanks and regards!

**Comment by iangray001** [comment]
Ah yes, there will be an inherent size limit due to the way that we send the UI around that is going to cause you problems. If you look at [the code which prepares the UI data for sending from the ESP to the browser](https://github.com/s00500/ESPUI/blob/678a2ccf5334f1443002c5282d6dc3d068ca74c0/src/ESPUIclient.cpp#L281), you will see that it does detect and handle overflow, but it does it by adding each control one at a time. In other words it assumes that each control is less than the total buffer size.

The proper solution is going to be to serve your image in the same way that we serve the js/css/html files. We don't have a way to extend extra files into the build process, but I'll explain how it works here and it should be pretty straightforward for you to hack in. Maybe if someone has time we could extend this properly.

[prepare_static_ui_sources.py](https://github.com/s00500/ESPUI/blob/master/tools/prepare_static_ui_sources.py) turns the HTML and Javascript files into C header files. For example, [data/index.htm](https://github.com/s00500/ESPUI/blob/master/data/index.htm) becomes [src/dataIndexHTML.h](https://github.com/s00500/ESPUI/blob/master/src/dataIndexHTML.h). These header files are included at the top of [ESPUI.cpp](https://github.com/s00500/ESPUI/blob/master/src/ESPUI.cpp). These are then served from a set of callbacks that are created from [line 1316](https://github.com/s00500/ESPUI/blob/678a2ccf5334f1443002c5282d6dc3d068ca74c0/src/ESPUI.cpp#LL1316C7-L1316C7) onwards. 

Unfortunately [prepare_static_ui_sources.py](https://github.com/s00500/ESPUI/blob/master/tools/prepare_static_ui_sources.py) only handles `.html`, `.css`, and `.js` files, but I quickly hacked it to also handle the raw binary files of GIFs. I'm not merging that because it is a silly bodge, but you can see the edits [in this gist](https://gist.github.com/iangray001/65f8077d38f1f6be6ce18fe0f7196f23) from line 68. Use this modified script:

```
tools/prepare_static_ui_sources.py --nostoremini --source data/animated.gif --target src/animated.h
```

and it will output an `animated.h` that contains the GZIPped and converted GIF. Include the new header in ESPUI.cpp:

```
#include "animated.h"
```

Then add a handler to ESPUI.cpp from line 68 or so that will be something like:

```
    server->on("animated.gif", HTTP_GET, [](AsyncWebServerRequest* request) {
        AsyncWebServerResponse* response
            = request->beginResponse_P(200, "image/gif", GIF_ANIMATED_GZIP, sizeof(GIF_ANIMATED_GZIP));
        response->addHeader("Content-Encoding", "gzip");
        request->send(response);
    });
```

I've not tested all this, but it should all just work.

**Comment by serlancelot** [comment]
Hello! Thank you for your answer!!, for the moment I will leave it as I have it since it works for me. I don't have much of a level, so I'll look at it to see if I can figure out how it works (I'm sure it will be easy, but not for me, I'm not a programmer).

In any case, what you indicated to me at the beginning helped me a lot, because as I told you, I thought it was only for static images! So Thank you very much!!
