### ISSUE TITLE
Enhancement: Only upload gzipped data to the ESP?

### ISSUE THREAD

**Issue by orithena** [s00500/ESPUI#39]
I'm wondering whether it is necessary to upload non-gzipped data to the ESP at all, since [all browsers support Content-Encoding: gzip](https://webmasters.stackexchange.com/questions/22217/which-browsers-handle-content-encoding-gzip-and-which-of-them-has-any-special).

Doing so would save a lot of space in PROGMEM ... for example, the minified `style.css` is at 19.5KB, while its gzipped data is a 2.8KB byte array (when compiled). We could save `*.min.<type>.gz` files in the `examples/gui/data` directory (for the sketch data uploader tool) and move the original HTML/CSS/JS files somewhere else. Then we can lose the minified data from the `*.h` files and keep only the gzipped byte array.

Since I know it's rather easy (for me, at least ^^) to modify the `prepare_static_ui_sources.py` script to reflect such a directory structure, this would actually be viable. Some library code would need refactoring, too, I assume (I didn't look too deep into the source code). 

Probably it would be best to serve original files if they do exist in SPIFFS (to ease the HTML/CSS/JS edit-deploy-run development cycle) and only serve gzipped versions if they're the only version.

Thoughts? Comments? Did I overlook something? Would this approach break old projects that decide to update the ESPUI library?

**Comment by s00500** [comment]
Actually it is not necessary at all, infact this is only used when you use prepareFilesystem() and then beginSPIFFS()

If the compiler does it's work correctly it should also never get compiled into the binary and uploaded to the esp and never be stored in memory when there is no reference to prepareFilesystem()
(I actually tested that, feel free to retry, checking stuff twice is always better)

Therefore it would technically not make the code use less memory most of the time...

And no it would probably not break things, I just left it there because I thought if somebody still goes the extra route of using prepareFileSystem (And there are obvious speed advantages to that) then it would be the easier way... 

The research question here would be how   
`server->serveStatic("/", SPIFFS, "/").setDefaultFile("index.htm");`
From ESPAsyncWebserver behaves if the files on SPIFFS are already gzipped (Its very likley to be fine though...)

**Comment by orithena** [comment]
Oh, the optimizer does its job for once ^^

Regarding that last part... I'd assume that we might have to convince the ESPAsyncWebserver to actually set the `Content-Encoding: gzip` header. But that remains to be tested.

Another thought: If we enhance the preparation script with an SCSS compiler (there actually is a module for that), we'd open the door for easy CSS themeing, cause that allows for multiple CSS files to be merged.

OTOH, that would create a definite dependency on a python environment for any changes on the CSS files.

**Comment by s00500** [comment]
I guess if somebody wants to change stuff he/she will figure out how to set up the python environment

For all other users we could provide some functions that load different themes while still relying on the optimizer to remove the rest of them

What do you think?

If you like to include SCSS feel free to do so :-)

**Comment by s00500** [comment]
@orithena Can I close this issue? and also: any chance to see you at 35C5 ?

**Comment by orithena** [comment]
@s00500 Did not come around yet to implement anything on this... so this issue currently serves as a reminder to implement that feature.

Also, I won't be at 35c3 this year... next year again! :)

**Comment by s00500** [comment]
@orithena Hey, currently at 36c3, I think we should close this issue and formulate further tasks as followups, are you around here ?

**Comment by orithena** [comment]
Dangit, yeah, I've been at 36c3 but only now checked up on github notifications... m)

Sounds about right, your plan with closing the issue. BTW, I gotta get back on projects where I actually use ESPUI, else I never get anything done here :)
