### ISSUE TITLE
Accelerometer control

### ISSUE THREAD

**Issue by shaurya0406** [s00500/ESPUI#49]
ACCELEROMETER control can be added to ESPUI

For reference:  https://www.instructables.com/id/Esp8266Websockets-RGB-LED-controller/
                          https://github.com/rahul-thakoor/rgbSliderfiles/blob/master/indexRGB.html

I was not able to modify it to use with ESP32 so I thought that this can be included in ESPUI.

**Comment by s00500** [comment]
Hey, that sounds like a really cool Idea, 
how do you think this should be done?
Shall we just make a option for the slider component? Or shall we create a new seperate component? And If so how do you think this could look and work?

Here is a nice demo of the event handlers from mozilla
https://mdn.mozillademos.org/en-US/docs/Web/API/Detecting_device_orientation$samples/Orientation_example?revision=1408844

**Comment by shaurya0406** [comment]
A separate component would be better and a small widget with an accelerometer symbol.

**Comment by shaurya0406** [comment]
I always have 2 versions of esp32 slave robot,one with ESPUI and another with ESPNOW so that I can use joysticks and accelerometer connected to controller remote. I want to have one uniform platform for my esp32 projects preferably ESPUI

**Comment by s00500** [comment]
Ok, what also comes to my mind here is that we should have some way of using such a widget with a mouse... otherwise it is useless on a laptop

**Comment by shaurya0406** [comment]
It would be great!!
A complete solution to all sorts of RC projects

**Comment by s00500** [comment]
Hm... there is an issue here.... since IOS 13 apple safari needs request permission, and that does not work outside or secure contexts... so we would need some tls running, that makes stuff more complicated...

https://github.com/me-no-dev/ESPAsyncWebServer/issues/377
https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140

So meanwhile this is not really possible unfortunately for all devices...
