### ISSUE TITLE
min/max values for text control

### ISSUE THREAD

**Issue by az-z** [s00500/ESPUI#76]
hello,
 is there parameters to control a min/max lenght for ControlType::Text ?

**Comment by s00500** [comment]
No currently not, but this should be implemented in the callback probably... whats you exact usecase ?

**Comment by az-z** [comment]
I want to set the min/max length for the input text.
Say password or wifi net name.
Handling that in a main program is ugly.

**Comment by iangray001** [comment]
[A few commits ago I merged in support for this](https://github.com/s00500/ESPUI/blob/fa097ce3293f98c6efdd021ada191bb5a815877b/data/js/controls.js#L440).

However, I also added to the README that you do still have to handle these limits in the ESP software because user input should not be trusted. It is trivial for the client to send whatever they want regardless of what the HTML says.
