### ISSUE TITLE
Values from all controls on the page/Accessing a control by name

### ISSUE THREAD

**Issue by az-z** [s00500/ESPUI#88]
I apologize for filing so many tickets. I file 2 questions in a single ticket.

1. Is there a way to cycle thru all existing controls and obtain their values?
e.g I have 4 numbers, 3 text, and one option controls,  there is only one button.
 to obtain values from all these controls i can think of 2 methods: 
 a. write 4+3+1 callbacks
 b. write one callback for a button and cycle thru all controls' values. 
how can I accomplish "b" without manually listing all controls?

2.  in a callback, how can I access a particular control? is there a name? I see there is some kind of id, but not sure what does it mean of how it can be used.

**Comment by s00500** [comment]
1: since arduino is single threaded one simple solution would be to use global variables and store values in each callback

2: when you create a control you get back it's index basically. This can be used to identify the control. To get parameters of this control use the getControl function first and then use the pointer to the control to retrieve it's parameters
eg:
Serial.println(ESPUI.getControl(switchOne)->value);

**Comment by az-z** [comment]
@s00500  Lukas, thank you for a quick reply.
the getControl returns Control :
`Control *getControl(uint16_t id);`

is there a way to use it in the "case" so i can have one callback function instead of 8 ?

**Comment by s00500** [comment]
you mean a switch statement ? You can switch on the ESPUI.getControl(switchOne)->type for the enum defined in ESPUI.h

roughly like 
switch() {
case ControlType::Button:
break;
}

Try to read the code in ESPUI.h and ESPUI.cpp and learn from it ;-)

**Comment by az-z** [comment]
yes, i saw that technique in the examples. 
i think the only way is to have an array of ids and in the callback go over the array and read associated values from controls..
thank you Lukas!
