### ISSUE TITLE
Dynamic addition of options wont work as expected

### ISSUE THREAD

**Issue by lindner8712** [s00500/ESPUI#98]
**Describe the bug**
Hello, im not sure if its really a bug, maybe just a missunderstanding of hanlding and usage from my side.
after try to add dynamic items to options with a "for" loop
the Text of the options stays empty, after clicking on the emtpy field, the resopnse is OK!

**To Reproduce**
1. use Example TabbedGUI
2. after init part of Option (line 213)

`for(int z=0;z<10;z++)`
`{  `
  `String sLabel="OptionDyn";`
  `String sOption="Opt";`
  `sLabel+=String(z);`
  `sOption+=String(z);`
  `const char* cLabel=sLabel.c_str();`
  `const char* cOption=sOption.c_str();`
  `ESPUI.addControl( ControlType::Option, cLabel, cOption, ControlColor::Alizarin, select1 );`
`}`
compile and download to ESP32

**Expected behavior**
option labels shold be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/8461050/96788263-7f615d00-13f3-11eb-88d2-b5172c5f2713.png)

ESPUI is up to date, also Arduino IDE

may you have some advice for me,
thank you very much in advance

**Comment by RubiRubsn** [comment]
Same problem here with the esp8266 and the esp32

**Comment by thomastech** [comment]
I spent the afternoon investigating this issue. And I have a proposed solution.

The _label_ parameter is current declared as a **const char***. Changing all instances of it to a **const String&** solves the problem. Both the ESPUI.h and ESPUI.cpp files need to be patched. 

BTW, there is no need to apply this fix to the _value_ argument since it is already declared as a String.

Here is example startup code I used to validate the fix:
```
  uint16_t select10 = ESPUI.addControl(ControlType::Select, "SelectDyn:", "", ControlColor::Alizarin, Control::noParent, &selectExample);
  String sLabel;
  String sValue;
  sLabel.reserve(12);
  sValue.reserve(6);
  for(int z=1; z<=6; z++) {
    sLabel="OptionDyn";
    sValue="Opt";
    sLabel+=String(z);
    sValue+=String(z);
    ESPUI.addControl(ControlType::Option, sLabel, sValue, ControlColor::Alizarin, select10);
  }
```

The attached zip file contains a patched version of the 2.0.2 release (which is old, but stable). The updated files also have the ESP32 LITTLEFS patch too (see my issue #144).
[ESPUI_Issue98.zip](https://github.com/s00500/ESPUI/files/7798556/ESPUI_Issue98.zip)

- Thomas

**Comment by Jojo-1000** [comment]
Dynamic strings currently do not work without extra effort because only the `const char*` is saved inside the controls, instead of making a copy.
The `String` objects are deleted after each iteration of the for loop, or at the end of the function, so this does not have the desired effect.

Always making a copy is definitely the safer choice, however I would argue that most users of this library will just call the version of `addControl` with a string literal `"Label"`. This does not require a copy, because the string is stored in static memory.
When the function receives a `const String&` called, this would cause two unnecessary copies of the string. First, a new `String` is created for the parameter, and second it is copied into the Control.

So there is a tradeoff of always copying the label, because it will use more memory in most cases.

Whithout making changes to the library, the strings must be stored somewhere they are not deleted:

```cpp
// Outside of any function body:
String optionLabels[10];

// In a function:
void addSelect()
{
  uint16_t select10 = ESPUI.addControl(ControlType::Select, "SelectDyn:", "", ControlColor::Alizarin, Control::noParent, &selectExample);
  String sValue;
  sValue.reserve(6);
  for(int z=0;z<10;z++)
  {
    String sZ = String(z);
    optionLabels[z].reserve(12);
    optionLabels[z] ="OptionDyn";
    optionLabels[z] += sZ;
    sValue = "Opt";
    sValue+=sZ;
    const char* cLabel=optionLabels[z].c_str();
    ESPUI.addControl( ControlType::Option, cLabel, sValue, ControlColor::Alizarin, select10);
  }
}
```

So it is possible, but one needs to decide whether saving string copies in most cases is worth this amount of effort in these special cases.

**Comment by thomastech** [comment]
Thanks for the explanation on why the label arg uses const char declarations rather than const string. But if achieving the smallest memory footprint is the goal then it is very strange that the _value_ arg uses a string type (which intrudes on this concept). So a bit of Jekyll and Hyde is going on here.

But regardless, your idea is brilliant. Just declare a global label string. Done! No changes to the library, no fuss.

I'd say this issue is resolved and recommend it be closed.

- Thomas

**Comment by s00500** [comment]
Thanks all, I will check the LittleFS issue too
